| Criterion               | Result         | Evidence and Explanation                                                                                                                                                                                                                                                   | How it was Tested/Measured                                                                                                                            |
| ----------------------- | -------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------- |
| Student management      | **Met**        | Testers were able to add, edit and remove students successfully. This was confirmed by Mr Marshall, Mrs Dardel and Alex Menzies during beta testing.                                                                                                                       | Testers completed Add Student, Edit Student and Remove Student scenarios and provided feedback through the beta testing surveys.                      |
| Status management       | **Met**        | The software allows students to have Missing, Late or Submitted statuses. Beta testers found the status management useful for identifying and managing incomplete work.                                                                                                    | Testers added and edited students and checked that their work status could be changed and displayed correctly.                                        |
| Filtering               | **Partly Met** | Class, status and Student ID filters work, but beta testers found the filtering could be easier to use. Some testers also wanted a separate sorting function for statuses.                                                                                                 | Testers used the available filters to find students and provided feedback about how easy they were to understand and use.                             |
| Search                  | **Met**        | The software allows users to search for students using their name or Student ID, making it quicker to locate records.                                                                                                                                                      | Search was tested by entering student names and IDs and checking whether the correct students were displayed.                                         |
| Reminders               | **Met**        | The Missing Work Reminders page identifies students whose status is Missing and displays the number of students requiring attention. Beta testers found reminders useful.                                                                                                  | Testers created or viewed students with Missing status and checked that they appeared on the reminders page.                                          |
| Data saving and loading | **Partly Met** | Student information is stored in JSON account files and can be loaded when the user logs in. However, the original requirement expected status changes to be saved automatically, so this area could be improved.                                                          | Data was entered, changed and then checked after saving/logging back into the account to confirm that information was retained.                       |
| Usability               | **Partly Met** | The main interface is simple and organised, but beta testers identified several usability issues. Login/account creation was more complicated than necessary, some input requirements were unclear, and Add/Edit/Remove buttons were difficult for some testers to locate. | Mr Marshall, Mrs Dardel and Alex Menzies used the finished software and completed beta testing surveys describing difficulties and positive features. |
| Performance             | **Met**        | The software runs as a lightweight Python/Tkinter application and does not require large hardware or internet resources. No major performance problems were identified during testing.                                                                                     | Testers used the software on a laptop/computer and checked whether pages, searches and filters responded appropriately.                               |
| Security                | **Partly Met** | User accounts require usernames and passwords, and account data is separated into individual JSON files. However, the system is a local application and does not provide advanced security features such as encryption or a database server.                               | Account creation and login were tested by creating accounts and attempting to log in with account details.                                            |

Future Evaluation

The software should be evaluated again after future improvements are made. A teacher such as Mr Marshall could test the system during normal marking over a period of several weeks. They would be responsible for checking whether student management, status updates, filtering, reminders and navigation are easy to use during real marking tasks.

The software should also be tested again after changes to the login system, input instructions, buttons and filtering. The same types of beta testers could complete the same scenarios so the new results can be compared with the original testing results. This would show whether the recommended changes actually improved usability.
